### ISSUE TITLE
Failed to activate the git-difftool package

### ISSUE THREAD

**Issue by chodorowicz** [felixkiss/atom-git-difftool#10]
[Enter steps to reproduce below:]

1. Install package - it fails during initialization

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [git-difftool](https://github.com/felixkiss/atom-git-difftool) package, v0.2.4

### Stack Trace

Failed to activate the git-difftool package

```
At '0' is not a valid selector in /Users/cho/.atom/packages/git-difftool/package.json

Error: '0' is not a valid selector in /Users/cho/.atom/packages/git-difftool/package.json
    at exports.validateSelector (/Applications/Atom.app/Contents/Resources/app/src/selector-validator.js:36:13)
    at CommandRegistry.module.exports.CommandRegistry.add (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:50:9)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:722:74
    at Package.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/package.js:750:21)
    at Package.module.exports.Package.subscribeToActivationCommands (/Applications/Atom.app/Contents/Resources/app/src/package.js:753:12)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:446:29
  at /Users/cho/.atom/packages/git-difftool/package.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "**/bower_components/*",
      "**/node_modules/*"
    ],
    "disabledPackages": [
      "symbols-tree-view",
      "slash-closer",
      "term2",
      "atom-terminal"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.0
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.1
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
dash, v1.0.3
editorconfig, v0.3.0
emmet, v2.3.4
highlight-selected, v0.9.1
html-helper, v0.2.3
line-ending-converter, v1.0.0
linter, v0.12.0
linter-jshint, v0.1.0
linter-php, v0.0.11
minimap, v4.5.0
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.2
php-twig, v3.0.0
project-manager, v1.15.5
project-palette-finder, v2.4.16
svg-preview, v0.5.1
tree-view-open-files, v0.2.3
zentabs, v0.8.2

# Dev
No dev packages
```

**Comment by KylePDavis** [comment]
I can also reproduce. Happens every time I open an Atom window.

**Comment by sergiolepore** [comment]
Same here after upgrading to Atom@0.187.0

**Atom Version:** 0.187.0
**System:** Ubuntu 14.04.2
**Thrown From:** git-difftool package, v0.2.4

**Comment by say2joe** [comment]
I also receive the same error.

**Comment by javierlopezdeancos** [comment]
the same error for me

Atom Version: 0.187.0
System: Mac 10.10
Thrown From: git-difftool package, v0.2.4

**Comment by felixkiss** [comment]
Please update to v0.2.5
